import { TypeProfile } from './types';

export const TYPE_PROFILES: Record<string, TypeProfile> = {
  explorer: {
    type: 'explorer',
    nameZh: '探索者', nameEn: 'EXPLORER', emoji: '🔵',
    color: '#6366f1', bgColor: 'bg-indigo-50',
    tagline: '靠直覺與體驗連結記憶，在不熟悉的情境中突然「頓悟」',
    brainwave: 'θ 創意波（4–8 Hz）', bestTime: '早晨 / 傍晚',
    varkLabel: 'K 動覺為主', primaryVark: 'kinesthetic',
    memoryTraits: [
      '記憶點常與特殊體驗、旅行、突破性事件綁定',
      '情境記憶強，非線性學習，跳躍式頓悟',
      '在全新陌生環境中反而學得更快',
    ],
    bestMethods: [
      '角色扮演和沉浸式情境練習',
      '去實際使用語言的地方（旅行、語言交換）',
      '把新詞彙連結到親身故事或難忘的冒險',
      '自由對話優先於結構化練習',
    ],
    avoidMethods: ['純背單字表（無情境連結）', '長時間重複同樣的材料'],
    week1to4: '每週一個全新主題，強調情境沉浸，挑戰自己進入從未嘗試的場景',
    week5to8: '旅行情境、角色扮演、與母語者的真實對話',
    week9to12: '整合輸出——用目標語言寫旅遊日記、講述親身故事',
    quote: '你的記憶活在故事裡，越真實的體驗，越永恆的記憶。',
  },

  architect: {
    type: 'architect',
    nameZh: '建築師', nameEn: 'ARCHITECT', emoji: '🟣',
    color: '#8b5cf6', bgColor: 'bg-violet-50',
    tagline: '系統性架構記憶，需要清晰的邏輯框架才能長期保留',
    brainwave: 'β 專注波（13–30 Hz）', bestTime: '9–11am / 2–4pm',
    varkLabel: 'R 讀寫為主', primaryVark: 'reading',
    memoryTraits: [
      '善於建立知識體系，筆記與結構化整理是主要工具',
      '需要理解原理才能真正記住，不喜歡「照單全收」',
      '框架記憶，邏輯驅動，理解例外規則後記得更牢',
    ],
    bestMethods: [
      '系統學習文法規則，理解每條規則的原因',
      '詞根詞彙分析，建立詞彙知識網路',
      '精讀文章，做結構化筆記',
      '思維導圖整理語法點和詞彙關係',
    ],
    avoidMethods: ['沒有框架的大量輸入', '太快跳到口說（需要先建立內部系統）'],
    week1to4: '文法框架建立，做完整的語法筆記系統，確保理解每條規則的邏輯',
    week5to8: '詞彙詞根分析，閱讀理解精讀，擴展知識體系',
    week9to12: '寫作輸出，把腦中的框架轉化為流暢的語言運用',
    quote: '你的大腦是一座精密建築，每塊磚都有邏輯位置。',
  },

  melodist: {
    type: 'melodist',
    nameZh: '旋律人', nameEn: 'MELODIST', emoji: '🟠',
    color: '#f59e0b', bgColor: 'bg-amber-50',
    tagline: '音調、韻律、語感是主要記憶鉤子，透過聲音形成長期記憶',
    brainwave: 'α 放鬆波（8–13 Hz）', bestTime: '下午 / 傍晚',
    varkLabel: 'A 聽覺為主', primaryVark: 'auditory',
    memoryTraits: [
      '最容易透過重複聆聽和跟讀記住內容',
      '節奏感強的輸入效果最好，音韻記憶',
      '說錯的地方往往因為「聽起來不對」才察覺',
    ],
    bestMethods: [
      'Shadowing（跟讀模仿）是核心練習方式',
      '每天聽同一段音頻 7–10 次，感受韻律變化',
      '學目標語言的歌曲，利用旋律記憶詞彙',
      'Podcast 沉浸法，不求全懂，先感受語感',
    ],
    avoidMethods: ['靜態閱讀為主的學習', '大量書面語法練習'],
    week1to4: 'Shadowing 訓練，選定 3–5 段核心音頻反覆操練，模仿到自然為止',
    week5to8: '歌曲學習 + 語調模仿，每週一首新歌深度學習',
    week9to12: '錄音自評，對比原版，持續調整語感和發音',
    quote: '語言對你來說是音樂，當你感受到節奏，記憶就自然流入。',
  },

  narrator: {
    type: 'narrator',
    nameZh: '敘事者', nameEn: 'NARRATOR', emoji: '🟡',
    color: '#eab308', bgColor: 'bg-yellow-50',
    tagline: '透過故事與情感連結記憶，對話與敘事是最強的輸入通道',
    brainwave: 'α+θ 雙波', bestTime: '傍晚 / 夜間',
    varkLabel: 'A+K 混合', primaryVark: 'auditory',
    memoryTraits: [
      '能把抽象概念轉化成有人物情節的故事來儲存',
      '情感連結越強，記憶越深，越持久',
      '對話和敘事是最強的輸入通道',
    ],
    bestMethods: [
      '用目標語言讀小說、看電影、聽有聲書',
      '和語言夥伴深入聊天（不是練習，是真正的對話）',
      '把新詞彙編進自己的生命故事或想像的劇情',
      '閱讀後寫下你的感受和情感聯想',
    ],
    avoidMethods: ['抽離情境的枯燥重複', '純粹記憶詞表或語法規則'],
    week1to4: '每週選一部電影 / 小說，深度沉浸，不求全懂，先感受情感',
    week5to8: '語言日記，每天用目標語言寫一段故事或心情',
    week9to12: '找語言夥伴，每週一次深度對話，聊真實的人生故事',
    quote: '你用故事理解世界，也用故事記住語言。',
  },

  connector: {
    type: 'connector',
    nameZh: '織網者', nameEn: 'CONNECTOR', emoji: '🟢',
    color: '#10b981', bgColor: 'bg-emerald-50',
    tagline: '跨領域連結能力強，記憶時自動與已有知識形成網狀關係',
    brainwave: 'α 放鬆波', bestTime: '午後',
    varkLabel: 'A+R 混合', primaryVark: 'reading',
    memoryTraits: [
      '最適合用類比、隱喻、跨學科整合來學習',
      '學習時自動尋找不同領域的連結點',
      '關聯記憶，知識網路越豐富，新知越容易記住',
    ],
    bestMethods: [
      '把語言學習和其他興趣整合（用目標語言學烹飪、音樂等）',
      '雙語閱讀，對比兩種語言的表達差異和共通點',
      '跨話題的廣泛閱讀，讓詞彙在不同語境中自然出現',
      '透過討論和社群形成知識網路',
    ],
    avoidMethods: ['單一主題的長期深度反覆（容易無聊）', '孤立地背單字'],
    week1to4: '用目標語言探索 3 個不同興趣領域，建立多角度詞彙',
    week5to8: '雙語內容對比，找語言差異和共通點，建立跨語言理解',
    week9to12: '主題整合輸出——用目標語言做一個跨領域的分享或討論',
    quote: '你的記憶像一張無邊的網，每個新知識都是一個節點。',
  },

  analyst: {
    type: 'analyst',
    nameZh: '分析師', nameEn: 'ANALYST', emoji: '🔴',
    color: '#ef4444', bgColor: 'bg-red-50',
    tagline: '深度分析後才能真正記住，透過教學來強化記憶',
    brainwave: 'β 專注波', bestTime: '上午',
    varkLabel: 'R+K 混合', primaryVark: 'reading',
    memoryTraits: [
      '淺層重複對他們幾乎無效，需要完全理解原理',
      '透過教別人、輸出來強化記憶',
      '原理記憶，輸出驅動，分析錯誤比重複正確更有效',
    ],
    bestMethods: [
      '深度分析語言錯誤，找出規律和根本原因',
      '費曼學習法——把學到的規則教給別人',
      '精讀文章，分析作者的表達選擇和邏輯結構',
      '建立「錯誤日誌」，每週回顧分析自己的錯誤模式',
    ],
    avoidMethods: ['看完就過、不求甚解的大量輸入', '只聽不分析'],
    week1to4: '系統分析目標語言的核心文法邏輯，建立個人語法分析筆記',
    week5to8: '精讀分析，深度研究詞彙用法，建立詞彙使用資料庫',
    week9to12: '教學輸出——錄製語言解說影片，或寫語言分析文章',
    quote: '你不只是在學語言，你在理解語言如何運作。',
  },

  performer: {
    type: 'performer',
    nameZh: '表演者', nameEn: 'PERFORMER', emoji: '🌸',
    color: '#ec4899', bgColor: 'bg-pink-50',
    tagline: '透過表達與互動鞏固記憶，說出來、演出來是記住的時刻',
    brainwave: 'γ 警覺波（30–50 Hz）', bestTime: '早上 / 中午',
    varkLabel: 'K+A 混合', primaryVark: 'kinesthetic',
    memoryTraits: [
      '語言課的最佳學習者類型，互動和即時反饋是核心驅動',
      '說出來之後才真的記住，輸出記憶',
      '需要觀眾或互動對象，獨自學習效率最低',
    ],
    bestMethods: [
      '頻繁的真人對話練習，越多越好',
      '語言角色扮演和即興對話練習',
      '用目標語言做簡報、拍影片、或教別人',
      '參加語言學習社群，成為活躍成員',
    ],
    avoidMethods: ['長時間獨自學習沒有互動', '過度追求「準備好再開口」'],
    week1to4: '每天至少一次語言輸出（錄音日記、語音訊息、網路對話）',
    week5to8: '參加語言交換或會話課，每週至少兩次真人互動',
    week9to12: '公開展演——用目標語言做一個分享、表演或教學',
    quote: '語言在你開口的那一刻活了起來。',
  },

  visionary: {
    type: 'visionary',
    nameZh: '圖像家', nameEn: 'VISIONARY', emoji: '🔶',
    color: '#f97316', bgColor: 'bg-orange-50',
    tagline: '視覺化是主要記憶通道，空間記憶法和圖解天生有效',
    brainwave: 'γ 警覺波', bestTime: '早上',
    varkLabel: 'V 視覺為主', primaryVark: 'visual',
    memoryTraits: [
      '看到圖就能記住複雜概念，空間記憶法特別有效',
      '圖像驅動，腦中的視覺化越清晰，記憶越持久',
      '說明白就能記住，描述出來比讀出來更有效',
    ],
    bestMethods: [
      '視覺化詞彙學習（圖片 + 單字 + 場景）',
      '看電影、影片學語言（搭配字幕）',
      '心智圖和圖解筆記，把知識畫出來',
      '記憶宮殿法——把詞彙放進空間位置',
    ],
    avoidMethods: ['純音頻學習（無視覺支撐）', '大量純文字閱讀'],
    week1to4: '建立視覺詞彙系統，每個詞彙配一張圖像或場景截圖',
    week5to8: '電影和影片沉浸，製作場景截圖詞彙本，一格一格學',
    week9to12: '圖解輸出——把學到的語法規則和詞彙網路畫成圖表',
    quote: '你用眼睛記住世界，圖像就是你的語言。',
  },
};
