create table if not exists public.talent_game_events (
  id bigint generated by default as identity primary key,
  client_event_id text not null unique,
  anonymous_id text not null,
  session_id text not null,
  event_name text not null check (event_name in (
    'session_started', 'screen_viewed', 'daily_reward_claimed',
    'scenario_started', 'scenario_abandoned', 'scenario_completed',
    'round_viewed', 'card_selected', 'answer_submitted',
    'card_upgraded', 'analytics_preference_changed'
  )),
  occurred_at timestamptz not null,
  scenario_id text,
  round_index integer,
  card_id text,
  talent text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists talent_game_events_event_time_idx on public.talent_game_events (event_name, occurred_at desc);
create index if not exists talent_game_events_scenario_idx on public.talent_game_events (scenario_id, round_index, occurred_at desc);
create index if not exists talent_game_events_card_idx on public.talent_game_events (card_id, occurred_at desc);

alter table public.talent_game_events enable row level security;

drop policy if exists "anonymous game event insert" on public.talent_game_events;
create policy "anonymous game event insert"
on public.talent_game_events for insert
to anon, authenticated
with check (
  length(anonymous_id) between 8 and 100
  and length(session_id) between 8 and 100
  and occurred_at > now() - interval '7 days'
  and occurred_at < now() + interval '5 minutes'
  and (round_index is null or round_index between 0 and 20)
  and jsonb_object_length(properties) <= 20
);

comment on table public.talent_game_events is 'Privacy-safe MemoQuest product events. Never store answer text, audio, email, name, or account identifiers.';
